apiVersion: app/v1
kind: Deployment
metadata:
  name: ok-app
spec:
  template:
    spec:
      containers:
      - name: ok-app-container
        image: europe-west3-docker.pkg.dev/k8s-k3s-421323/k8s-k3s/demo:v1.0.0
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.25"
            memory: "256Mi"
