apiVersion: v1
kind: Pod
metadata:
  name: ok-app
spec:
  template:
    spec:
      containers:
      - name: ok-app-container
        image: europe-west3-docker.pkg.dev/k8s-k3s-421323/k8s-k3s/demo:v1.0.0
        readinessProbe:
          httpGet:
            path: /readiness
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
        - containerPort: 8000
          name: http