apiVersion: app/v1
kind: Pod
metadata:
  name: ok-app-pod
spec:
  containers:
  - name: ok-app-container
    image: europe-west3-docker.pkg.dev/k8s-k3s-421323/k8s-k3s/demo:v1.0.0
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret1
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret1
            key: password
  restartPolicy: Never


